"""adiciona campos verification code

Revision ID: 0cd58c913601
Revises: b90be32279a0
Create Date: 2026-05-25 21:26:15.076132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd58c913601'
down_revision: Union[str, Sequence[str], None] = 'b90be32279a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('verification_code_expires_at', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_code_expires_at')
        batch_op.drop_column('verification_code')

    # ### end Alembic commands ###

UPGRADE_SQL = [
    "ALTER TABLE users ADD COLUMN verification_code TEXT",
    "ALTER TABLE users ADD COLUMN verification_code_expires_at TEXT",
]

DOWNGRADE_SQL = [
    "ALTER TABLE users DROP COLUMN verification_code_expires_at",
    "ALTER TABLE users DROP COLUMN verification_code",
]